baseURL: 'https://www.jonaharagon.com/'
languageCode: en-us
title: 'Jonah Aragon'
theme: WonderMod

# Code Highlight
pygmentsstyle: "monokai"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    style: monokai

params:
  author: Jonah Aragon
  description: Jonah Aragon is creating educational resources for average people to understand the importance of privacy and security on the internet, and take back control over their digital lives.
  keywords:
    - privacy
    - technology
    - security
  env: production

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  showtoc: true
  defaultTheme: auto

  mainSections:
     - posts
     - techlore-talks

  assets:
    disableHLJS: true

  homeInfoParams:
    Title: "Hi, I'm Jonah \U0001F44B"
    Content: |
      Jonah Aragon is creating educational resources for average people to understand the importance of privacy and security on the internet, and take back control over their digital lives. 
      
      He is known for his work on the [Techlore](https://www.youtube.com/playlist?list=PL3KeV6Ui_4CZRb5Z4qZjsIGZrUWbDc3Mn) YouTube channel, including the [Techlore Talks](/techlore-talks/) podcast he co-hosts, and the [Privacy Guides](https://www.privacyguides.org) non-profit website.

  socialIcons:
    - name: Mastodon
      url: "https://mastodon.neat.computer/@jonah"
    - name: KoFi
      url: https://ko-fi.com/jonaharagon
    - name: OMG.lol
      url: "https://jonah.omg.lol"
    - name: YouTube
      url: "https://www.youtube.com/user/jonaharagon"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/jonaharagon/"
    - name: GitHub
      url: "https://github.com/jonaharagon"
    - name: CV
      url: 'cv'

menu:
  main:
    - identifier: accounts
      name: Accounts
      url: accounts
      weight: 10
    - identifier: blog
      name: Blog
      url: posts
      weight: 20
    - identifier: newsletter
      name: Newsletter
      url: https://jonaharagon.substack.com/
      weight: 30
    - identifier: cv
      name: CV
      url: cv
      weight: 40
