[build]
    publish = "public/"
    command = "hugo"

[context.production.environment]
    PRODUCTION = "true"

[[redirects]]
    from = "/posts/linus-tech-tips-hacked-whos-to-blame/"
    to = "https://jonaharagon.neat.pub/2023/03/24/who-is-really-to-blame-for-the-linus-tech-tips-hack/"
    force = true

[[redirects]]
    from = "/posts/in-defense-of-internet-anonymity/"
    to = "https://jonaharagon.neat.pub/2022/10/30/in-defense-of-internet-anonymity/"
    force = true

[[redirects]]
    from = "/posts/macos-ventura-security-and-privacy/"
    to = "https://jonaharagon.neat.pub/2022/10/27/new-privacy-and-security-features-in-macos-13-ventura/"
    force = true

[[redirects]]
    from = "/posts/privacytools-considered-harmful/"
    to = "https://jonaharagon.neat.pub/2022/09/25/what-is-the-deal-with-privacytools/"
    force = true

[[redirects]]
    from = "/posts/toxicity-and-fanboyism-in-the-privacy-community/"
    to = "https://jonaharagon.neat.pub/2022/02/08/toxicity-and-fanboyism-in-the-privacy-community/"
    force = true

[[redirects]]
    from = "/posts/threat-modeling/"
    to = "https://jonaharagon.neat.pub/2021/09/13/threat-modeling-the-first-skill-you-need-to-begin-your-privacy-journey/"
    force = true

[[redirects]]
    from = "/posts/the-trouble-with-vpn-and-privacy-review-sites/"
    to = "https://jonaharagon.neat.pub/2019/11/20/the-trouble-with-vpn-and-privacy-review-sites/"
    force = true

[[redirects]]
    from = "/posts/choosing-a-vpn/"
    to = "https://jonaharagon.neat.pub/2019/10/30/choosing-a-vpn/"
    force = true

[[redirects]]
    from = "/posts/understanding-vpns/"
    to = "https://jonaharagon.neat.pub/2019/10/05/understanding-vpns/"
    force = true

[[redirects]]
    from = "/posts/apple-independent-repair-provider-program/"
    to = "https://jonaharagon.neat.pub/2019/09/01/thoughts-on-apples-independent-repair-program/"
    force = true

[[redirects]]
    from = "/posts/self-hosting-shadowsocks-vpn-outline/"
    to = "https://jonaharagon.neat.pub/2019/08/22/self-hosting-a-shadowsocks-vpn-with-outline/"
    force = true

[[redirects]]
    from = "/posts/enabling-pushover-notifications-on-successful-ssh-logins/"
    to = "https://jonaharagon.neat.pub/2019/05/15/enabling-pushover-notifications-on-ssh-logins/"
    force = true

[[redirects]]
    from = "/posts/securing-services-with-tor-and-alt-svc/"
    to = "https://jonaharagon.neat.pub/2019/05/07/securing-services-with-tor-and-alt-svc/"
    force = true

[[redirects]]
    from = "/posts/creating-bootable-macos-usb-installers/"
    to = "https://jonaharagon.neat.pub/2018/11/21/creating-bootable-macos-usb-installers/"
    force = true
